services:

  mysql:
    image: mysql:8.0
    container_name: software_subscription_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyRootPass123
      MYSQL_DATABASE: software_subscription
      MYSQL_USER: appuser
      MYSQL_PASSWORD: AppPass123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - traefik

  app:
    build: .
    container_name: software_subscription_app
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;database=software_subscription;user=appuser;password=AppPass123;"
    depends_on:
      - mysql

    networks:
      - traefik

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.software.rule=Host(`dayan3.devtscape.org`)"
      - "traefik.http.routers.software.entrypoints=websecure"
      - "traefik.http.routers.software.tls=true"
      - "traefik.http.routers.software.tls.certresolver=production"
      - "traefik.http.services.software.loadbalancer.server.port=8080"


volumes:
  mysql_data:


networks:
  traefik:
    external: true
